### ISSUE TITLE
Bill of Material

### ISSUE THREAD

**Issue by GregoireH** [adamfeuer/hackeeg-shield#4]
Hello Adam,

Thanks for this nice repo !
Amazing job.

I was wondering if you would have a BOM somewhere that you could add to the git repo.
I guess I am not the first one to look for this.
And If I need to go through each component and look for them online, it will take quite some time, and I fear that I may mis-order some parts.

Finally, a friendly way of allowing people to generate a BOM from your designs is to add attributes to each components,
This can be anything from Manufacturer part number to more custom references.
It is also pretty useful when you want to make a new design reusing parts of a former design.
In such a way you can quickly check the availability of a given part.

If you provide the BOM I can add the attribute to your design and propose a pull request so that it just add that. Not modifying anything else of course !

Thanks in advance
Have a nice day

**Comment by GregoireH** [comment]
It is not an issue but a proposal of improvement.

Best

**Comment by adamfeuer** [comment]
@GregoireH Hi, I'm planning on offering this for sale soon. Once I have production verified, I will add the BOM.

**Comment by GregoireH** [comment]
Hi @adamfeuer,

Thanks for the update.

Do you have any timeline in mind for the release ? I need to start looking into it soon, as I would like to integrate it on another project where I am almost done.

I already ordered your board from seedstudio, that's why I was now looking for components.
If you can share a BOM (even privately: gregoire dot heitz at gmail dot com) I would be extremely happy
Otherwise I will have to make it myself tomorrow.

Thanks in advance,
Have a nice day

Ps if i can help you in anyway, please let me know

**Comment by adamfeuer** [comment]
@GregoireH Let's take this to email, you can email me at adam@starcat.io.
